/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.ControladorReparaciones;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Alejandro.perezferna
 */
public class VistaReparaciones extends javax.swing.JDialog {

    /**
     * Creates new form VistaReparaciones
     */
    public VistaReparaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ControladorReparaciones.IniciarSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmpleadoID = new javax.swing.JTextField();
        btnRepararVehiculo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCosteReparacion = new javax.swing.JTextField();
        txtCosteReparacion1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmatricula1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnFinalizarReparacion = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reparaciones");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Matricula:");

        jLabel2.setText("Empleado ID:");

        btnRepararVehiculo.setText("Reparar Vehiculo");
        btnRepararVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepararVehiculoActionPerformed(evt);
            }
        });

        jLabel3.setText("Coste de la reparacion:");

        jLabel5.setText("Coste final de la reparacion:");

        jLabel6.setText("Matricula:");

        btnFinalizarReparacion.setText("Finalizar Reparacion");
        btnFinalizarReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarReparacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmatricula)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpleadoID)
                            .addComponent(txtCosteReparacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRepararVehiculo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmatricula1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtCosteReparacion1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnFinalizarReparacion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRepararVehiculo)
                    .addComponent(txtEmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(txtCosteReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnFinalizarReparacion))
                .addGap(18, 18, 18)
                .addComponent(txtCosteReparacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ControladorReparaciones.CerrarSession();
    }//GEN-LAST:event_formWindowClosed

    private void btnRepararVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepararVehiculoActionPerformed
        // TODO add your handling code here:
        ControladorReparaciones.RepararVehiculo();
    }//GEN-LAST:event_btnRepararVehiculoActionPerformed

    private void btnFinalizarReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarReparacionActionPerformed
        // TODO add your handling code here:
        ControladorReparaciones.FinalizarReparacion();
    }//GEN-LAST:event_btnFinalizarReparacionActionPerformed

    public JButton getBtnRepararVehiculo() {
        return btnRepararVehiculo;
    }

    public JTextField getTxtCosteReparacion() {
        return txtCosteReparacion;
    }

    public JTextField getTxtEmpleadoID() {
        return txtEmpleadoID;
    }

    public JTextField getTxtmatricula() {
        return txtmatricula;
    }

    public JButton getBtnFinalizarReparacion() {
        return btnFinalizarReparacion;
    }

    public JTextField getTxtCosteReparacion1() {
        return txtCosteReparacion1;
    }

    public JTextField getTxtmatricula1() {
        return txtmatricula1;
    }

   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarReparacion;
    private javax.swing.JButton btnRepararVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCosteReparacion;
    private javax.swing.JTextField txtCosteReparacion1;
    private javax.swing.JTextField txtEmpleadoID;
    private javax.swing.JTextField txtmatricula;
    private javax.swing.JTextField txtmatricula1;
    // End of variables declaration//GEN-END:variables
}
